enum AppRoutes {
  MAIN = 'main',
  HOME = 'home',
  REGISTER = 'register',
  LOGIN = 'login',
  FORGOT_PASSWORD = 'forgot_password',
  RESET_PASSWORD = 'reset_password',
  PROFILE = 'profile',
  PROFILE_PROFILE = 'profile_profile',
  PROFILE_ORDERS = 'profile_orders',
  PROFILE_ORDERS_ORDER = 'profile_orders_order',
  NOT_FOUND = 'not_found',
  INGREDIENTS = 'ingredients',
  FEED = 'feed',
  FEED_BASE = 'feed_base',
  FEED_ORDER = 'feed_order',
}

export const RoutePath: Record<AppRoutes, string> = {
  [AppRoutes.MAIN]: '/',
  [AppRoutes.HOME]: '/home',
  [AppRoutes.INGREDIENTS]: '/ingredients/:ingredientId',
  [AppRoutes.REGISTER]: '/register',
  [AppRoutes.LOGIN]: '/login',
  [AppRoutes.FORGOT_PASSWORD]: '/forgot-password',
  [AppRoutes.RESET_PASSWORD]: '/reset-password',
  [AppRoutes.PROFILE]: '/profile',
  [AppRoutes.PROFILE_PROFILE]: '/profile/profile',
  [AppRoutes.PROFILE_ORDERS]: '/profile/orders',
  [AppRoutes.PROFILE_ORDERS_ORDER]: '/profile/orders/:orderId',
  [AppRoutes.FEED]: '/feed',
  [AppRoutes.FEED_BASE]: '/feed/base',
  [AppRoutes.FEED_ORDER]: '/feed/:feedId',
  [AppRoutes.NOT_FOUND]: '*',
};
